# Generated by Django 3.1.2 on 2020-11-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('param_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='userType',
            new_name='user_type',
        ),
    ]
