# Generated by Django 3.1.2 on 2020-11-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('param_app', '0002_auto_20201108_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, 'vip'), (3, 'svip')], max_length=21),
        ),
    ]
