# Generated by Django 3.1.2 on 2020-11-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
