# Generated by Django 3.1.2 on 2020-11-12 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pageapp', '0002_auto_20201112_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tb_company',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageapp.company')),
            ],
            options={
                'db_table': 'tb_phone',
            },
        ),
    ]
